name: Daily Auto Commit

on:
  schedule:
    - cron: '0 9 * * *' # Har kuni soat 09:00 da ishlaydi
  workflow_dispatch: # Manuel ishga tushirish uchun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Oxirgi yangilanish: $(date)" > daily_update.txt

      - name: Commit and Push
        run: |
          git config --global user.name "ruzmamatov99"
          git config --global user.email "kamolbekrozmamatov@gmail.com"
          git add daily_update.txt
          git commit -m "Daily contribution: $(date)"
          git push
