name: Daily 8 Commits

on:
  schedule:
    # Har 3 soatda bir marta ishga tushadi (GMT bo'yicha)
    - cron: '0 */3 * * *'
  workflow_dispatch: # O'zingiz xohlagan paytda tugmani bosib ishga tushirish uchun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Activity File
        run: |
          echo "Oxirgi faollik: $(date)" > activity_log.txt

      - name: Commit and Push
        run: |
          git config --global user.name "ruzmamatov99"
          git config --global user.email "kamolbekrozmamatov@gmail.com"
          git add activity_log.txt
          git commit -m "Frontend update: $(date)"
          git push
